/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "PAYLOAD_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PayloadCmsWebsite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "TURSO_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}